YAKALANAN POLİÇLERİN KAYDEDİLECEĞİ TABLO

CREATE TABLE `muhasebe_yakalananpoliceler` (
	`ID` INT(11) NOT NULL AUTO_INCREMENT,
	`SigortaSirketi` INT(3) NOT NULL COMMENT 'sigortasirketi tablosu ile relational',
	`PoliceTuru` INT(11) NOT NULL COMMENT 'sigortapoliceturleri tablosuyla ilişkilidir.',
	`PoliceNumarasi` VARCHAR(25) NOT NULL COLLATE 'latin5_turkish_ci',
	`Plaka` VARCHAR(30) NOT NULL COLLATE 'latin5_turkish_ci',
	`TanzimTarihi` DATE NOT NULL,
	`BaslangicTarihi` DATE NOT NULL,
	`BitisTarihi` DATE NOT NULL,
	`BrutPrim` FLOAT NOT NULL DEFAULT '0',
	`NetPrim` FLOAT NOT NULL DEFAULT '0',
	`SigortaliAdi` VARCHAR(70) NULL DEFAULT NULL COLLATE 'latin5_turkish_ci',
	`ProduktorID` INT(11) NOT NULL DEFAULT '0',
	`ProduktorSubeID` INT(11) NOT NULL DEFAULT '0',
	`UyeID` INT(10) NOT NULL,
	`SubeID` INT(10) NOT NULL,
	`FirmaID` INT(10) NOT NULL,
	`MusteriID` INT(11) NULL DEFAULT NULL,
	`CepTelefonu` INT(11) NULL DEFAULT NULL,
	`GuncelleyenUyeID` INT(10) NULL DEFAULT NULL,
	`DisPolice` TINYINT(1) NULL DEFAULT '0',
	`AcenteAdi` VARCHAR(70) NULL DEFAULT NULL COLLATE 'latin5_turkish_ci',
	`AcenteNo` VARCHAR(20) NOT NULL DEFAULT '' COLLATE 'latin5_turkish_ci',
	`EklenmeTarihi` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`GuncellenmeTarihi` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
	`Aciklama` VARCHAR(150) NULL DEFAULT NULL COLLATE 'latin5_turkish_ci',
	PRIMARY KEY (`ID`) USING BTREE,
	INDEX `idx_SigortaSirketi` (`SigortaSirketi`) USING BTREE,
	INDEX `idx_PoliceNumarasi` (`PoliceNumarasi`) USING BTREE,
	INDEX `idx_Plaka` (`Plaka`) USING BTREE,
	INDEX `TanzimTarihi` (`TanzimTarihi`) USING BTREE,
	INDEX `MusteriID` (`MusteriID`) USING BTREE,
	INDEX `ProduktorId` (`ProduktorID`) USING BTREE,
	INDEX `ProduktorSubeID` (`ProduktorSubeID`) USING BTREE,
	INDEX `CepTelefonu` (`CepTelefonu`) USING BTREE,
	INDEX `GuncelleyenUyeID` (`GuncelleyenUyeID`) USING BTREE,
	INDEX `DisPolice` (`DisPolice`) USING BTREE,
	INDEX `Tur` (`PoliceTuru`) USING BTREE,
	INDEX `AcenteNo` (`AcenteNo`) USING BTREE,
	INDEX `idx_SigortaSirketi_BrutPrim` (`SigortaSirketi`, `BrutPrim`) USING BTREE,
	INDEX `idx_FirmaID_EklenmeTarihi_Tanzim_DisPolice` (`FirmaID`, `EklenmeTarihi`, `TanzimTarihi`, `DisPolice`) USING BTREE,
	INDEX `idx_UyeID` (`UyeID`, `FirmaID`) USING BTREE,
	INDEX `idx_SubeID` (`SubeID`, `FirmaID`) USING BTREE,
	INDEX `idx_FirmaID` (`FirmaID`) USING BTREE,
	INDEX `idx_AcenteAdi` (`AcenteAdi`) USING BTREE,
	INDEX `idx_Tanzim_FirmaId` (`TanzimTarihi`, `FirmaID`) USING BTREE,
	INDEX `idx_FirmaID_SigortaliAdi` (`FirmaID`, `SigortaliAdi`, `TanzimTarihi`) USING BTREE
)
COMMENT='//Günlük üretim miktarı\r\nSELECT t.Turu, floor(SUM(y.brutprim)) AS Uretim, count(y.tur) AS Adet FROM muhasebe_yakalananpoliceler y left join sigortapoliceturleri t ON t.Id=y.Tur WHERE y.TanzimTarihi=\'2023-07-06\' GROUP BY y.Tur\r\nUNION\r\nSELECT Concat(y.TanzimTarihi, \' Toplam\'), floor(SUM(y.brutprim)), count(y.tur) FROM muhasebe_yakalananpoliceler y WHERE y.TanzimTarihi=\'2023-07-06\''
COLLATE='latin5_turkish_ci'
ENGINE=MyISAM
AUTO_INCREMENT=7102343
;



YETKİLERİN ÖZELLİKLERİNİN OLDUĞU TABLO (Gerekliliği şüpheli)

CREATE TABLE `muhasebe_yetkiadlari` (
	`ID` INT(11) NOT NULL AUTO_INCREMENT,
	`YetkiSirasi` SMALLINT(6) NULL DEFAULT NULL,
	`YetkiAdi` VARCHAR(70) NULL DEFAULT '' COLLATE 'latin5_turkish_ci',
	`YetkiAciklamasi` VARCHAR(250) NULL DEFAULT NULL COLLATE 'latin5_turkish_ci',
	UNIQUE INDEX `ID` (`ID`) USING BTREE
)
COLLATE='latin5_turkish_ci'
ENGINE=InnoDB
AUTO_INCREMENT=18
;

YETKİLERİN BULUNDUĞU TABLO

CREATE TABLE `muhasebe_yetkiler` (
	`ID` INT(10) NOT NULL AUTO_INCREMENT,
	`FirmaId` INT(1) NULL DEFAULT NULL,
	`EkleyenUyeID` INT(10) NOT NULL,
	`YetkiAdi` VARCHAR(150) NULL DEFAULT NULL COLLATE 'latin5_turkish_ci',
	`KayitTarihi` DATETIME NULL DEFAULT NULL,
	`GuncellemeTarihi` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	`GorebilecegiPolicelerveKartlar` CHAR(1) NULL DEFAULT '2' COMMENT '1- Tüm kartları ve poliçeleri görebilir\r\n2- Sadece kendi şubesinin poliçelerini ve kartlarını görür.\r\n3- Sadece kendi poliçelerini ve kartlarını görür.\r\n4- Hiçbir poliçe ve kartı göremez.' COLLATE 'latin5_turkish_ci',
	`PoliceYakalamaSecenekleri` CHAR(1) NULL DEFAULT '0' COLLATE 'latin5_turkish_ci',
	`ProduktorleriGorebilsin` CHAR(1) NULL DEFAULT '0' COMMENT 'Bu değer 0 olarak ayarlanırsa prodüktörler kısmında sadece kendini görebilir.' COLLATE 'latin5_turkish_ci',
	`PoliceDuzenleyebilsin` CHAR(1) NULL DEFAULT '0' COMMENT 'Bu değer 1 olarak ayarlanırsa poliçe havuzunda ki poliçeleri silebilir, düzenleyebilir anlamına gelir.' COLLATE 'latin5_turkish_ci',
	`PoliceDosyalarinaErisebilsin` CHAR(1) NULL DEFAULT '0' COMMENT 'GorebileceğiPolicelerveKartlar yetkisiyle bağlı olarak bu yetki 1 olursa police dosyalarına erişebilir.' COLLATE 'latin5_turkish_ci',
	`PoliceAktarabilsin` CHAR(1) NULL DEFAULT '0' COMMENT 'Bu değer 1 olarak ayarlanırsa poliçe aktarmasına müsaade edilir.' COLLATE 'latin5_turkish_ci',
	`PoliceHavuzunuGorebilsin` CHAR(1) NULL DEFAULT '0' COLLATE 'latin5_turkish_ci',
	`YetkilerSayfasindaIslemYapabilsin` CHAR(1) NULL DEFAULT '0' COMMENT 'Bu değer 1 olarak ayarlanırsa yetkiler sayfasını görebilir ve işlem yapabilir.' COLLATE 'latin5_turkish_ci',
	`AcenteliklerSayfasindaIslemYapabilsin` CHAR(1) NULL DEFAULT '0' COMMENT 'Bu değer 1 olarak ayarlanırsa acentelikler sayfasını görebilir ve işlem yapabilir.' COLLATE 'latin5_turkish_ci',
	`KomisyonOranlariniDuzenleyebilsin` CHAR(1) NULL DEFAULT '0' COLLATE 'latin5_turkish_ci',
	`AcenteliklereGorePoliceYakalansin` CHAR(1) NULL DEFAULT '1' COMMENT 'Bu değer 1 olarak ayarlanırsa acenteliklerede bulunan acenteliklere göre yakalama yapılır. Acenteliklerde bulunmayan acente kodlarından gelen poliçeler sunucuya kaydedilmez' COLLATE 'latin5_turkish_ci',
	UNIQUE INDEX `ID` (`ID`) USING BTREE,
	INDEX `EkleyenUyeID` (`EkleyenUyeID`) USING BTREE,
	INDEX `FirmaId` (`FirmaId`) USING BTREE
)
COLLATE='latin5_turkish_ci'
ENGINE=MyISAM
ROW_FORMAT=DYNAMIC
AUTO_INCREMENT=3104
;


ÜRETİM TABLOSU SON HALİ (Bazı sütunların amacı ve gerekliliği anlamadım)

CREATE TABLE `muhasebe_police_v2` (
	`Id` INT(11) NOT NULL AUTO_INCREMENT,
	`PoliceTipi` CHAR(50) NOT NULL COMMENT 'T=Tahakkuk, I=İptal' COLLATE 'utf8_turkish_ci',
	`PoliceNo` VARCHAR(50) NOT NULL COLLATE 'utf8_turkish_ci',
	`ZeyilNo` TINYINT(4) NOT NULL DEFAULT '0',
	`Plaka` VARCHAR(11) NOT NULL DEFAULT '' COLLATE 'utf8_turkish_ci',
	`YenilemeNo` TINYINT(4) NULL DEFAULT NULL,
	`SigortaSirketiId` INT(11) NOT NULL,
	`TanzimTarihi` DATETIME NOT NULL,
	`BaslangicTarihi` DATETIME NOT NULL,
	`BitisTarihi` DATETIME NOT NULL,
	`SigortaEttirenId` INT(11) NOT NULL DEFAULT '0',
	`BrutPrim` DECIMAL(12,2) NOT NULL DEFAULT '0.00',
	`NetPrim` DECIMAL(12,2) NOT NULL DEFAULT '0.00',
	`Vergi` DECIMAL(12,2) NOT NULL DEFAULT '0.00',
	`Komisyon` DECIMAL(12,2) NOT NULL DEFAULT '0.00',
	`BransId` INT(11) NOT NULL,
	`DisPolice` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '0=İç Poliçe, 1=Dış Poliçe',
	`MusteriID` INT(11) NULL DEFAULT NULL,
	`PoliceTespitKaynakId` INT(1) NULL DEFAULT NULL COMMENT 'muhasebe_policetespitkaynagi referansı',
	`IsOrtagiFirmaId` INT(11) NOT NULL DEFAULT '0',
	`IsOrtagiSubeId` INT(11) NOT NULL DEFAULT '0',
	`IsOrtagiUyeId` INT(11) NOT NULL DEFAULT '0',
	`IsOrtagiKomisyonOrani` DECIMAL(5,2) NOT NULL DEFAULT '0.00',
	`IsOrtagiKomisyon` DECIMAL(12,2) NOT NULL DEFAULT '0.00',
	`IsOrtagiEslestirmeKriteri` INT(11) NOT NULL DEFAULT '0',
	`IsOrtagiOnayDurumu` BIT(1) NULL DEFAULT NULL,
	`KaynakDosyaID` INT(4) NOT NULL DEFAULT '0',
	`KayitDurumu` TINYINT(4) NOT NULL DEFAULT '1',
	`OnayDurumu` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '0=Beklemede (Havuz), 1=Onaylandı, 2=Reddedildi',
	`EklenmeTarihi` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`GuncellenmeTarihi` DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
	`GuncelleyenKullaniciId` INT(10) NOT NULL DEFAULT '0',
	PRIMARY KEY (`Id`) USING BTREE,
	UNIQUE INDEX `uk_PoliceNo_Zeyil_Sirket` (`PoliceNo`, `ZeyilNo`, `SigortaSirketiId`) USING BTREE,
	INDEX `idx_OnayDurumu` (`OnayDurumu`) USING BTREE,
	INDEX `idx_FirmaId_OnayDurumu` (`IsOrtagiFirmaId`, `OnayDurumu`) USING BTREE,
	INDEX `idx_SigortaSirketiId` (`SigortaSirketiId`) USING BTREE,
	INDEX `idx_TanzimTarihi` (`TanzimTarihi`) USING BTREE,
	INDEX `idx_BaslangicTarihi` (`BaslangicTarihi`) USING BTREE,
	INDEX `idx_BitisTarihi` (`BitisTarihi`) USING BTREE,
	INDEX `idx_BransId` (`BransId`) USING BTREE,
	INDEX `idx_MusteriID` (`MusteriID`) USING BTREE,
	INDEX `idx_Plaka` (`Plaka`) USING BTREE,
	INDEX `idx_PoliceNo` (`PoliceNo`) USING BTREE,
	INDEX `idx_IsOrtagiUyeId` (`IsOrtagiUyeId`) USING BTREE,
	INDEX `idx_IsOrtagiSubeId` (`IsOrtagiSubeId`) USING BTREE,
	INDEX `idx_KaynakDosyaID` (`KaynakDosyaID`) USING BTREE,
	INDEX `idx_KayitDurumu` (`KayitDurumu`) USING BTREE,
	INDEX `idx_Firma_Onay_Tanzim` (`IsOrtagiFirmaId`, `OnayDurumu`, `TanzimTarihi`) USING BTREE,
	INDEX `idx_Sirket_Kaynak_Kayit_Onay` (`SigortaSirketiId`, `KaynakDosyaID`, `KayitDurumu`, `OnayDurumu`) USING BTREE
)
COMMENT='Birleştirilmiş poliçe tablosu. OnayDurumu=0 eski havuz, OnayDurumu=1 onaylı poliçeler.'
COLLATE='utf8_turkish_ci'
ENGINE=MyISAM
;


CREATE TABLE `muhasebe_police` (
	`Id` INT(11) NOT NULL AUTO_INCREMENT,
	`PoliceTipi` CHAR(50) NOT NULL COLLATE 'utf8_turkish_ci',
	`PoliceNo` VARCHAR(50) NOT NULL COLLATE 'utf8_turkish_ci',
	`ZeyilNo` TINYINT(4) NOT NULL,
	`Plaka` VARCHAR(11) NOT NULL DEFAULT '' COLLATE 'utf8_turkish_ci',
	`YenilemeNo` TINYINT(4) NULL DEFAULT NULL,
	`SigortaSirketiId` INT(11) NOT NULL,
	`TanzimTarihi` DATETIME NOT NULL,
	`BaslangicTarihi` DATETIME NOT NULL,
	`BitisTarihi` DATETIME NOT NULL,
	`SigortaEttirenId` INT(11) NOT NULL,
	`BrutPrim` DECIMAL(12,2) NOT NULL,
	`NetPrim` DECIMAL(12,2) NOT NULL,
	`Vergi` DECIMAL(12,2) NOT NULL,
	`Komisyon` DECIMAL(12,2) NOT NULL,
	`BransId` INT(11) NOT NULL,
	`DisPolice` TINYINT(1) NOT NULL DEFAULT '0',
	`MusteriID` INT(11) NULL DEFAULT NULL,
	`PoliceTespitKaynakId` INT(1) NULL DEFAULT NULL,
	`IsOrtagiFirmaId` INT(11) NOT NULL,
	`IsOrtagiSubeId` INT(11) NOT NULL,
	`IsOrtagiUyeId` INT(11) NOT NULL,
	`IsOrtagiKomisyonOrani` DECIMAL(5,2) NOT NULL,
	`IsOrtagiKomisyon` DECIMAL(12,2) NOT NULL,
	`IsOrtagiEslestirmeKriteri` INT(11) NOT NULL,
	`IsOrtagiOnayDurumu` BIT(1) NULL DEFAULT NULL,
	`KaynakDosyaID` INT(4) NOT NULL DEFAULT '0',
	`KayitDurumu` TINYINT(4) NOT NULL,
	`EklenmeTarihi` DATETIME NOT NULL,
	`GuncellenmeTarihi` DATETIME NULL DEFAULT NULL,
	`GuncelleyenKullaniciId` INT(10) NOT NULL,
	`Kur` DECIMAL(10,4) NULL DEFAULT '1.0000' COMMENT 'Döviz kuru',
	`Aciklama` TEXT NULL DEFAULT NULL COMMENT 'Poliçe açıklaması' COLLATE 'utf8_turkish_ci',
	`TahsilatAciklamasi` TEXT NULL DEFAULT NULL COMMENT 'Tahsilat açıklaması' COLLATE 'utf8_turkish_ci',
	`PoliceKesenPersonel` VARCHAR(255) NULL DEFAULT NULL COMMENT 'Poliçeyi kesen personel' COLLATE 'utf8_turkish_ci',
	`Sube` VARCHAR(255) NULL DEFAULT NULL COMMENT 'Şube bilgisi' COLLATE 'utf8_turkish_ci',
	`YenilemeDurumu` VARCHAR(100) NULL DEFAULT NULL COMMENT 'Yenileme durumu' COLLATE 'utf8_turkish_ci',
	`UretimTuru` VARCHAR(100) NULL DEFAULT NULL COMMENT 'Üretim türü' COLLATE 'utf8_turkish_ci',
	`KayitSekli` VARCHAR(100) NULL DEFAULT NULL COMMENT 'Kayıt şekli' COLLATE 'utf8_turkish_ci',
	`TaksitDurumu` VARCHAR(100) NULL DEFAULT NULL COMMENT 'Taksit durumu' COLLATE 'utf8_turkish_ci',
	`TaksitSayisi` INT(11) NULL DEFAULT NULL COMMENT 'Taksit sayısı',
	`OdemeTipi` VARCHAR(100) NULL DEFAULT NULL COMMENT 'Ödeme tipi' COLLATE 'utf8_turkish_ci',
	`MptsDurumu` VARCHAR(100) NULL DEFAULT NULL COMMENT 'MPTS durumu' COLLATE 'utf8_turkish_ci',
	`Mutabakat` VARCHAR(100) NULL DEFAULT NULL COMMENT 'Mutabakat bilgisi' COLLATE 'utf8_turkish_ci',
	`NetKazanc` DECIMAL(10,2) NULL DEFAULT NULL COMMENT 'Net kazanç',
	`Iskonto` DECIMAL(10,2) NULL DEFAULT NULL COMMENT 'İskonto tutarı',
	PRIMARY KEY (`Id`) USING BTREE,
	UNIQUE INDEX `IxPolicePoliceNo` (`PoliceNo`, `ZeyilNo`, `SigortaSirketiId`) USING BTREE,
	INDEX `SirketIdveKaynakDosyaAdiveKayitDurumu` (`SigortaSirketiId`, `KaynakDosyaID`, `KayitDurumu`) USING BTREE,
	INDEX `PoliceTespitKaynakId` (`PoliceTespitKaynakId`) USING BTREE,
	INDEX `MusteriId` (`MusteriID`) USING BTREE,
	INDEX `IsOrtagiUyeId` (`IsOrtagiUyeId`) USING BTREE,
	INDEX `IsOrtagiSubeId` (`IsOrtagiSubeId`) USING BTREE,
	INDEX `IsOrtagiFirmaId` (`IsOrtagiFirmaId`) USING BTREE,
	INDEX `PoliceNo` (`PoliceNo`) USING BTREE,
	INDEX `ZeyilNo` (`ZeyilNo`) USING BTREE,
	INDEX `TanzimTarihi` (`TanzimTarihi`) USING BTREE,
	INDEX `BaslangicTarihi` (`BaslangicTarihi`) USING BTREE,
	INDEX `BitisTarihi` (`BitisTarihi`) USING BTREE,
	INDEX `BransId` (`BransId`) USING BTREE,
	INDEX `Plaka` (`Plaka`) USING BTREE
)
COLLATE='utf8_turkish_ci'
ENGINE=MyISAM
ROW_FORMAT=DYNAMIC
AUTO_INCREMENT=56936
;

MÜŞTERİ ARAÇ BİLGİLERİ 

CREATE TABLE `muhasebe_policearac_v2` (
	`Id` INT(11) NOT NULL AUTO_INCREMENT,
	`PoliceId` INT(11) NOT NULL COMMENT 'muhasebe_police_v2.Id referansı',
	`AracKodu` VARCHAR(7) NULL DEFAULT NULL COLLATE 'utf8_turkish_ci',
	`AracMarkaId` INT(11) NULL DEFAULT '0',
	`AracModelId` INT(11) NULL DEFAULT '0',
	`Plaka` VARCHAR(12) NULL DEFAULT NULL COLLATE 'utf8_turkish_ci',
	`ModelYili` SMALLINT(6) NULL DEFAULT NULL,
	`MotorNo` VARCHAR(25) NULL DEFAULT NULL COLLATE 'utf8_turkish_ci',
	`SasiNo` VARCHAR(25) NULL DEFAULT NULL COLLATE 'utf8_turkish_ci',
	`RuhsatBelgeNo` VARCHAR(25) NULL DEFAULT NULL COLLATE 'utf8_turkish_ci',
	`TescilTarihi` DATE NULL DEFAULT NULL,
	`KullanimTarziId` INT(11) NULL DEFAULT NULL,
	`YolcuSayisi` TINYINT(4) NULL DEFAULT NULL,
	`Agirlik` INT(11) NULL DEFAULT NULL,
	`MarkaModelVerisi` VARCHAR(500) NULL DEFAULT NULL COLLATE 'utf8_turkish_ci',
	`KayitDurumu` TINYINT(4) NOT NULL DEFAULT '1',
	`EklenmeTarihi` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`GuncellenmeTarihi` DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
	`GuncelleyenKullaniciId` INT(11) NOT NULL DEFAULT '0',
	PRIMARY KEY (`Id`) USING BTREE,
	INDEX `idx_PoliceId` (`PoliceId`) USING BTREE,
	INDEX `idx_AracModelId` (`AracModelId`) USING BTREE,
	INDEX `idx_AracMarkaId` (`AracMarkaId`) USING BTREE,
	INDEX `idx_AracKodu` (`AracKodu`) USING BTREE,
	INDEX `idx_Plaka` (`Plaka`) USING BTREE
)
COMMENT='Poliçe araç bilgileri V2'
COLLATE='utf8_turkish_ci'
ENGINE=MyISAM
;

HAVUZ POLİÇE TABLOSU (Bazı sütunların amacı ve gerekliliği anlamadım)

CREATE TABLE `muhasebe_policehavuz` (
	`Id` INT(11) NOT NULL AUTO_INCREMENT,
	`PoliceTipi` CHAR(50) NOT NULL COLLATE 'utf8_turkish_ci',
	`PoliceNo` VARCHAR(50) NOT NULL COLLATE 'utf8_turkish_ci',
	`Plaka` VARCHAR(11) NOT NULL COLLATE 'utf8_turkish_ci',
	`ZeyilNo` TINYINT(4) NOT NULL,
	`YenilemeNo` TINYINT(4) NULL DEFAULT NULL,
	`SigortaSirketiId` INT(11) NOT NULL,
	`TanzimTarihi` DATETIME NOT NULL,
	`BaslangicTarihi` DATETIME NOT NULL,
	`BitisTarihi` DATETIME NOT NULL,
	`SigortaEttirenId` INT(11) NOT NULL,
	`BrutPrim` DECIMAL(12,2) NOT NULL,
	`NetPrim` DECIMAL(12,2) NOT NULL,
	`Vergi` DECIMAL(12,2) NOT NULL,
	`Komisyon` DECIMAL(12,2) NOT NULL,
	`BransId` INT(11) NOT NULL,
	`DisPolice` TINYINT(1) NOT NULL DEFAULT '0',
	`MusteriID` INT(11) NOT NULL,
	`PoliceTespitKaynakId` INT(1) NOT NULL,
	`IsOrtagiFirmaId` INT(11) NOT NULL,
	`IsOrtagiSubeId` INT(11) NOT NULL,
	`IsOrtagiUyeId` INT(11) NOT NULL,
	`IsOrtagiKomisyonOrani` DECIMAL(5,2) NOT NULL,
	`IsOrtagiKomisyon` DECIMAL(12,2) NOT NULL,
	`IsOrtagiEslestirmeKriteri` INT(11) NOT NULL,
	`IsOrtagiOnayDurumu` BIT(1) NULL DEFAULT NULL,
	`KaynakDosyaID` INT(4) NOT NULL DEFAULT '0',
	`KayitDurumu` TINYINT(4) NOT NULL,
	`EklenmeTarihi` DATETIME NOT NULL,
	`GuncellenmeTarihi` DATETIME NULL DEFAULT NULL,
	`GuncelleyenKullaniciId` INT(10) NOT NULL,
	`Kur` DECIMAL(10,4) NULL DEFAULT '1.0000' COMMENT 'Döviz kuru',
	`Aciklama` TEXT NULL DEFAULT NULL COMMENT 'Poliçe açıklaması' COLLATE 'utf8_turkish_ci',
	`TahsilatAciklamasi` TEXT NULL DEFAULT NULL COMMENT 'Tahsilat açıklaması' COLLATE 'utf8_turkish_ci',
	`PoliceKesenPersonel` VARCHAR(255) NULL DEFAULT NULL COMMENT 'Poliçeyi kesen personel' COLLATE 'utf8_turkish_ci',
	`Sube` VARCHAR(255) NULL DEFAULT NULL COMMENT 'Şube bilgisi' COLLATE 'utf8_turkish_ci',
	`YenilemeDurumu` VARCHAR(100) NULL DEFAULT NULL COMMENT 'Yenileme durumu' COLLATE 'utf8_turkish_ci',
	`UretimTuru` VARCHAR(100) NULL DEFAULT NULL COMMENT 'Üretim türü' COLLATE 'utf8_turkish_ci',
	`KayitSekli` VARCHAR(100) NULL DEFAULT NULL COMMENT 'Kayıt şekli' COLLATE 'utf8_turkish_ci',
	`TaksitDurumu` VARCHAR(100) NULL DEFAULT NULL COMMENT 'Taksit durumu' COLLATE 'utf8_turkish_ci',
	`TaksitSayisi` INT(11) NULL DEFAULT NULL COMMENT 'Taksit sayısı',
	`OdemeTipi` VARCHAR(100) NULL DEFAULT NULL COMMENT 'Ödeme tipi' COLLATE 'utf8_turkish_ci',
	`MptsDurumu` VARCHAR(100) NULL DEFAULT NULL COMMENT 'MPTS durumu' COLLATE 'utf8_turkish_ci',
	`Mutabakat` VARCHAR(100) NULL DEFAULT NULL COMMENT 'Mutabakat bilgisi' COLLATE 'utf8_turkish_ci',
	`NetKazanc` DECIMAL(10,2) NULL DEFAULT NULL COMMENT 'Net kazanç',
	`Iskonto` DECIMAL(10,2) NULL DEFAULT NULL COMMENT 'İskonto tutarı',
	PRIMARY KEY (`Id`) USING BTREE,
	UNIQUE INDEX `IxPolicePoliceNo` (`PoliceNo`, `ZeyilNo`, `SigortaSirketiId`) USING BTREE,
	INDEX `SirketIdveKaynakDosyaAdiveKayitDurumu` (`SigortaSirketiId`, `KaynakDosyaID`, `KayitDurumu`, `PoliceTespitKaynakId`) USING BTREE,
	INDEX `PoliceNo` (`PoliceNo`) USING BTREE,
	INDEX `ZeyilNo` (`ZeyilNo`) USING BTREE,
	INDEX `IsOrtagiFirmaId` (`IsOrtagiFirmaId`) USING BTREE,
	INDEX `IsOrtagiSubeId` (`IsOrtagiSubeId`) USING BTREE,
	INDEX `IsOrtagiUyeId` (`IsOrtagiUyeId`) USING BTREE,
	INDEX `TanzimTarihi` (`TanzimTarihi`) USING BTREE,
	INDEX `BaslangicTarihi` (`BaslangicTarihi`) USING BTREE,
	INDEX `BitisTarihi` (`BitisTarihi`) USING BTREE,
	INDEX `MusteriID` (`MusteriID`) USING BTREE,
	INDEX `BransId` (`BransId`) USING BTREE,
	INDEX `Plaka` (`Plaka`) USING BTREE
)
COLLATE='utf8_turkish_ci'
ENGINE=MyISAM
ROW_FORMAT=DYNAMIC
AUTO_INCREMENT=56936
;

POLİÇE TÜRLERİNİN OLDUĞU TABLO

CREATE TABLE `sigortapoliceturleri` (
	`ID` INT(10) NOT NULL AUTO_INCREMENT,
	`Turu` CHAR(20) NULL DEFAULT NULL COLLATE 'latin5_turkish_ci',
	UNIQUE INDEX `ID` (`ID`) USING BTREE
)
COLLATE='latin5_turkish_ci'
ENGINE=MyISAM
ROW_FORMAT=DYNAMIC
AUTO_INCREMENT=256
;


Amacını anlamadığım tablolar:

CREATE TABLE `muhasebe_policerizikoadres_v2` (
	`Id` INT(10) NOT NULL AUTO_INCREMENT,
	`PoliceId` INT(10) NOT NULL COMMENT 'muhasebe_police_v2.Id referansı',
	`Adres` VARCHAR(300) NULL DEFAULT NULL COLLATE 'utf8_turkish_ci',
	`Alan` DECIMAL(8,2) NULL DEFAULT NULL,
	`IlId` INT(10) NULL DEFAULT NULL,
	`IlceId` INT(10) NULL DEFAULT NULL,
	`DainiMurtehinAdi` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8_turkish_ci',
	`BinaKodu` VARCHAR(10) NULL DEFAULT NULL COLLATE 'utf8_turkish_ci',
	`AdresNo` VARCHAR(10) NULL DEFAULT NULL COLLATE 'utf8_turkish_ci',
	`KayitDurumu` TINYINT(3) NOT NULL DEFAULT '1',
	`EklenmeTarihi` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`GuncellenmeTarihi` DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
	`GuncelleyenKullaniciId` INT(10) NOT NULL DEFAULT '0',
	PRIMARY KEY (`Id`) USING BTREE,
	INDEX `idx_PoliceId` (`PoliceId`) USING BTREE
)
COMMENT='Poliçe riziko adresleri V2'
COLLATE='utf8_turkish_ci'
ENGINE=MyISAM
;

CREATE TABLE `muhasebe_policerizikoadres` (
	`Id` INT(10) NOT NULL AUTO_INCREMENT,
	`PoliceId` INT(10) NOT NULL,
	`Adres` VARCHAR(300) NULL DEFAULT NULL COLLATE 'utf8_turkish_ci',
	`Alan` DECIMAL(8,2) NULL DEFAULT NULL,
	`IlId` INT(10) NULL DEFAULT NULL,
	`IlceId` INT(10) NULL DEFAULT NULL,
	`DainiMurtehinAdi` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8_turkish_ci',
	`BinaKodu` VARCHAR(10) NULL DEFAULT NULL COLLATE 'utf8_turkish_ci',
	`AdresNo` VARCHAR(10) NULL DEFAULT NULL COLLATE 'utf8_turkish_ci',
	`KayitDurumu` TINYINT(3) NOT NULL,
	`EklenmeTarihi` DATETIME NOT NULL,
	`GuncellenmeTarihi` DATETIME NULL DEFAULT NULL,
	`GuncelleyenKullaniciId` INT(10) NOT NULL,
	PRIMARY KEY (`Id`) USING BTREE
)
COLLATE='utf8_turkish_ci'
ENGINE=MyISAM
AUTO_INCREMENT=15094
;

CREATE TABLE `muhasebe_policesigortali_v2` (
	`Id` INT(10) NOT NULL AUTO_INCREMENT,
	`PoliceId` INT(10) NOT NULL COMMENT 'muhasebe_police_v2.Id referansı',
	`SigortaSahipId` INT(10) NOT NULL,
	`KayitDurumu` TINYINT(3) NOT NULL DEFAULT '1',
	`EklenmeTarihi` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`GuncellenmeTarihi` DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
	`GuncelleyenKullaniciId` INT(10) NOT NULL DEFAULT '0',
	PRIMARY KEY (`Id`) USING BTREE,
	INDEX `idx_PoliceId` (`PoliceId`) USING BTREE,
	INDEX `idx_SigortaSahipId` (`SigortaSahipId`) USING BTREE
)
COMMENT='Poliçe sigortalı bilgileri V2'
COLLATE='utf8_turkish_ci'
ENGINE=MyISAM
;

CREATE TABLE `muhasebe_policesigortali` (
	`Id` INT(10) NOT NULL AUTO_INCREMENT,
	`PoliceId` INT(10) NOT NULL,
	`SigortaSahipId` INT(10) NOT NULL,
	`KayitDurumu` TINYINT(3) NOT NULL,
	`EklenmeTarihi` DATETIME NOT NULL,
	`GuncellenmeTarihi` DATETIME NULL DEFAULT NULL,
	`GuncelleyenKullaniciId` INT(10) NOT NULL,
	PRIMARY KEY (`Id`) USING BTREE
)
COLLATE='utf8_turkish_ci'
ENGINE=MyISAM
AUTO_INCREMENT=57240
;


Müşteri tablosu

CREATE TABLE `muhasebe_musteriler` (
	`ID` INT(10) NOT NULL AUTO_INCREMENT,
	`SAHIPTURU` TINYINT(1) NULL DEFAULT '0',
	`TCKIMLIKNO` VARCHAR(11) NULL DEFAULT NULL COLLATE 'latin5_turkish_ci',
	`VERGINO` VARCHAR(10) NULL DEFAULT NULL COLLATE 'latin5_turkish_ci',
	`TCVERGINO` VARCHAR(11) NULL DEFAULT NULL COLLATE 'latin5_turkish_ci',
	`ADI` VARCHAR(150) NULL DEFAULT NULL COLLATE 'latin5_turkish_ci',
	`SOYADI` VARCHAR(30) NULL DEFAULT NULL COLLATE 'latin5_turkish_ci',
	`DOGUMYERI` VARCHAR(30) NULL DEFAULT NULL COLLATE 'latin5_turkish_ci',
	`DOGUMTARIHI` DATE NULL DEFAULT NULL,
	`CINSIYET` VARCHAR(10) NULL DEFAULT NULL COLLATE 'latin5_turkish_ci',
	`BABAADI` VARCHAR(70) NULL DEFAULT NULL COLLATE 'latin5_turkish_ci',
	`GSM` VARCHAR(23) NULL DEFAULT NULL COLLATE 'latin5_turkish_ci',
	`GSM2` VARCHAR(23) NULL DEFAULT NULL COLLATE 'latin5_turkish_ci',
	`TELEFON` VARCHAR(23) NULL DEFAULT NULL COLLATE 'latin5_turkish_ci',
	`EMAIL` VARCHAR(40) NULL DEFAULT NULL COLLATE 'latin5_turkish_ci',
	`MESLEK` VARCHAR(40) NULL DEFAULT NULL COLLATE 'latin5_turkish_ci',
	`YASADIGIIL` VARCHAR(20) NULL DEFAULT NULL COLLATE 'latin5_turkish_ci',
	`YASADIGIILCE` VARCHAR(20) NULL DEFAULT NULL COLLATE 'latin5_turkish_ci',
	`BOY` INT(10) NULL DEFAULT '0',
	`KILO` INT(10) NULL DEFAULT '0',
	`EKLEYENFIRMAID` INT(10) NULL DEFAULT NULL,
	`EKLEYENUYEID` INT(10) NULL DEFAULT NULL,
	`EKLEYENSUBEID` INT(10) NULL DEFAULT '0',
	`EKLENMEZAMANI` DATETIME NULL DEFAULT NULL,
	`GUNCELLENMEZAMANI` DATETIME NULL DEFAULT NULL,
	`GUNCELLEYENUYEID` INT(11) NULL DEFAULT NULL,
	UNIQUE INDEX `ID` (`ID`) USING BTREE,
	INDEX `TCVERGINO` (`TCVERGINO`) USING BTREE,
	INDEX `DogumTarihi` (`DOGUMTARIHI`) USING BTREE,
	INDEX `EklenmeZamani` (`EKLENMEZAMANI`) USING BTREE,
	INDEX `GuncellemeZamani` (`GUNCELLENMEZAMANI`) USING BTREE,
	INDEX `EkleyenFirmaId` (`EKLEYENFIRMAID`) USING BTREE,
	INDEX `EkleyenUyeId` (`EKLEYENUYEID`) USING BTREE,
	INDEX `EkleyenSubeId` (`EKLEYENSUBEID`) USING BTREE
)
COLLATE='latin5_turkish_ci'
ENGINE=MyISAM
ROW_FORMAT=DYNAMIC
AUTO_INCREMENT=14799720
;

Çalışan tablosu

CREATE TABLE `sigortakullanicilist` (
	`ID` INT(10) NOT NULL AUTO_INCREMENT,
	`FirmaId` INT(1) NULL DEFAULT NULL,
	`SubeId` INT(1) NULL DEFAULT '0',
	`HesapId` INT(1) NULL DEFAULT '0',
	`HesapYedekId` INT(1) NULL DEFAULT '0',
	`HesapYedek3Id` INT(1) NULL DEFAULT '0',
	`HesapYedek4Id` INT(1) NULL DEFAULT '0',
	`YetkiId` INT(1) NULL DEFAULT '0',
	`MuhasebeYetkiID` INT(1) NULL DEFAULT '0',
	`KomisyonOraniID` INT(1) NULL DEFAULT '0',
	`KomisyonId` INT(1) NULL DEFAULT '0',
	`KuralId` INT(1) NULL DEFAULT '0' COMMENT 'Bu Id sigortakuralzincirleri den beslenmektedir',
	`AnaYoneticimi` TINYINT(1) NULL DEFAULT '1' COMMENT '0 ise anayönetici,1 ise değil',
	`IpIstisnasiVarmi` TINYINT(1) NULL DEFAULT '0',
	`GeciciIPIstisnasi` TINYINT(4) NULL DEFAULT '0',
	`KullaniciTuru` INT(11) NULL DEFAULT '0',
	`EkleyenUyeId` INT(11) NULL DEFAULT '0',
	`Adi` VARCHAR(150) NULL DEFAULT NULL COLLATE 'latin5_turkish_ci',
	`Soyadi` VARCHAR(150) NULL DEFAULT NULL COLLATE 'latin5_turkish_ci',
	`Cinsiyet` CHAR(1) NULL DEFAULT 'B' COLLATE 'latin5_turkish_ci',
	`Email` VARCHAR(50) NULL DEFAULT NULL COLLATE 'latin5_turkish_ci',
	`Parola` VARCHAR(50) NULL DEFAULT NULL COLLATE 'latin5_turkish_ci',
	`FeedbackParola` VARCHAR(50) NULL DEFAULT NULL COLLATE 'latin5_turkish_ci',
	`SabitTel` VARCHAR(12) NULL DEFAULT NULL COLLATE 'latin5_turkish_ci',
	`GsmNo` VARCHAR(12) NULL DEFAULT NULL COLLATE 'latin5_turkish_ci',
	`GsmDogrulmaKodu` INT(10) NULL DEFAULT NULL,
	`KayitTarihi` DATETIME NULL DEFAULT NULL,
	`GuncellemeTarihi` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	`BitisTarihi` DATETIME NULL DEFAULT NULL,
	`SonGirisZamani` DATETIME NULL DEFAULT NULL,
	`SonGirisUyeGuid` INT(11) NULL DEFAULT NULL,
	`IpAdresi` VARCHAR(50) NULL DEFAULT NULL COLLATE 'latin5_turkish_ci',
	`IpAdresiEngelle` VARCHAR(30) NULL DEFAULT NULL COLLATE 'latin5_turkish_ci',
	`PcIdEngeli` VARCHAR(500) NULL DEFAULT NULL COLLATE 'latin5_turkish_ci',
	`PcIdGirisDurumu` TINYINT(1) NULL DEFAULT '0',
	`WebFirmaAdi` VARCHAR(30) NULL DEFAULT NULL COLLATE 'latin5_turkish_ci',
	`WebIlIlce` VARCHAR(30) NULL DEFAULT NULL COLLATE 'latin5_turkish_ci',
	`Onay` TINYINT(1) NULL DEFAULT '1',
	`OnaySozlesme` TINYINT(1) NULL DEFAULT '1',
	`PaslasmadaListelensin` TINYINT(1) NULL DEFAULT '0',
	`SigortaOnlineAlicisi` TINYINT(1) NULL DEFAULT '0',
	`LogoYolu` VARCHAR(100) NULL DEFAULT NULL COLLATE 'latin5_turkish_ci',
	`ProfilYolu` VARCHAR(100) NULL DEFAULT NULL COLLATE 'latin5_turkish_ci',
	`IBAN` VARCHAR(27) NULL DEFAULT NULL COLLATE 'latin5_turkish_ci',
	`WebSorguGondermeyecekSirketler` VARCHAR(250) NULL DEFAULT NULL COLLATE 'latin5_turkish_ci',
	`WebSorguAlicilar` VARCHAR(500) NULL DEFAULT NULL COLLATE 'latin5_turkish_ci',
	`PolicelestirmeTalepAlicilari` VARCHAR(500) NULL DEFAULT NULL COLLATE 'latin5_turkish_ci',
	`WebSorguAlicilarKasko` VARCHAR(500) NULL DEFAULT NULL COLLATE 'latin5_turkish_ci',
	`PolicelestirmeTalepAlicilariKasko` VARCHAR(500) NULL DEFAULT NULL COLLATE 'latin5_turkish_ci',
	`KomisyonOrani` INT(1) NULL DEFAULT '0',
	`CaptchaKontor` INT(1) NULL DEFAULT '0',
	`SMSTestHakkiKullanildi` TINYINT(1) NULL DEFAULT '0',
	`YeniSistemKullan` TINYINT(1) NULL DEFAULT '0',
	`ChromeEntegrasyonuYapildi` TINYINT(1) NULL DEFAULT '0',
	`WhatsappEntegrasyonuYapildi` TINYINT(1) NULL DEFAULT '0',
	`WhatsappEntegrasyonuYapildi2` TINYINT(1) NULL DEFAULT '0',
	`WhatsappEntegrasyonuTarihi2` DATETIME NULL DEFAULT NULL,
	`VirusKontroluSonucu` TINYINT(1) NULL DEFAULT '0',
	`VirusKontroluTarihi` DATETIME NULL DEFAULT NULL,
	`TamamlayiciSaglikCevabi` TINYINT(1) NULL DEFAULT '0',
	`CiftYonluDogrulamaYontemi` TINYINT(1) NULL DEFAULT '0' COMMENT '0 ise çift yönlü doğrulama yok.\r\n1 ise çift yönlü doğrulama etkin.\r\n2 ise sms ile giriş etkin.',
	`CiftYonluSecretKey` VARCHAR(50) NULL DEFAULT NULL COLLATE 'latin5_turkish_ci',
	`SonGirisVersiyon` VARCHAR(20) NULL DEFAULT NULL COLLATE 'latin5_turkish_ci',
	`SonGirisIslemci` VARCHAR(100) NULL DEFAULT NULL COLLATE 'latin5_turkish_ci',
	`SonGirisIslemciPuani` VARCHAR(10) NULL DEFAULT NULL COLLATE 'latin5_turkish_ci',
	`SonGirisRam` VARCHAR(6) NULL DEFAULT NULL COLLATE 'latin5_turkish_ci',
	`SonGirisWindowsBilgisi` VARCHAR(100) NULL DEFAULT NULL COLLATE 'latin5_turkish_ci',
	`Token` VARCHAR(800) NULL DEFAULT NULL COLLATE 'latin5_turkish_ci',
	`TokenExpiry` DATETIME NULL DEFAULT NULL,
	`RefreshToken` VARCHAR(255) NULL DEFAULT NULL COLLATE 'latin5_turkish_ci',
	`RefreshTokenExpiry` DATETIME NULL DEFAULT NULL,
	PRIMARY KEY (`ID`) USING BTREE,
	INDEX `Adi` (`Adi`) USING BTREE,
	INDEX `SoyAdi` (`Soyadi`) USING BTREE,
	INDEX `SonGirisUyeGuid` (`SonGirisUyeGuid`) USING BTREE,
	INDEX `idx_email_parola` (`Email`, `Parola`) USING BTREE,
	INDEX `Idx_SonGirisTarihi` (`SonGirisZamani`) USING BTREE,
	INDEX `Cinsiyet` (`Cinsiyet`) USING BTREE,
	INDEX `IBAN` (`IBAN`) USING BTREE,
	INDEX `Token` (`Token`) USING BTREE,
	INDEX `RefreshToken` (`RefreshToken`) USING BTREE,
	INDEX `Onay` (`Onay`) USING BTREE,
	INDEX `GsmNo` (`GsmNo`) USING BTREE
)
COMMENT='//Bitiş tarihlerini güncellemek için\r\nUPDATE sigortakullanicilist k left join sigortafirmalist f ON k.FirmaId = f.Id  SET k.bitistarihi=(k.bitistarihi + INTERVAL 100 MONTH)\r\nWHERE f.BitisTarihi >= NOW()\r\nAND k.BitisTarihi<=NOW()\r\nAND	k.SonGirisZamani >= NOW() - INTERVAL 1 MONTH'
COLLATE='latin5_turkish_ci'
ENGINE=MyISAM
ROW_FORMAT=DYNAMIC
AUTO_INCREMENT=27682
;

Sigorta Şirketleri

CREATE TABLE `muhasebe_sigortasirketi` (
	`Id` INT(10) NOT NULL AUTO_INCREMENT,
	`IdEski` INT(10) NULL DEFAULT NULL,
	`Kod` VARCHAR(3) NOT NULL DEFAULT '0' COLLATE 'utf8_turkish_ci',
	`Ad` VARCHAR(100) NOT NULL COLLATE 'utf8_turkish_ci',
	`SirketAdi` VARCHAR(30) NULL DEFAULT NULL COLLATE 'utf8_turkish_ci',
	`SirketAdiLatin` VARCHAR(30) NULL DEFAULT NULL COLLATE 'utf8_turkish_ci',
	`KayitDurumu` TINYINT(3) NOT NULL,
	`Faal` TINYINT(1) NOT NULL DEFAULT '1',
	`WebServis` TINYINT(4) NOT NULL DEFAULT '0',
	`EklenmeTarihi` DATETIME NOT NULL,
	`GuncellenmeTarihi` DATETIME NULL DEFAULT NULL,
	`GuncelleyenKullaniciId` INT(10) NULL DEFAULT NULL,
	PRIMARY KEY (`Id`) USING BTREE,
	INDEX `SirketAdi` (`SirketAdi`) USING BTREE,
	INDEX `Kod` (`Kod`) USING BTREE,
	INDEX `Ad` (`Ad`) USING BTREE,
	INDEX `Faal` (`Faal`) USING BTREE,
	INDEX `GuncelleyenKullaniciId` (`GuncelleyenKullaniciId`) USING BTREE
)
COLLATE='utf8_turkish_ci'
ENGINE=MyISAM
ROW_FORMAT=DYNAMIC
AUTO_INCREMENT=1000
;


Sigorta Şubeler 

CREATE TABLE `sigortasubeler` (
	`ID` INT(10) NOT NULL AUTO_INCREMENT,
	`FirmaId` INT(1) NULL DEFAULT NULL,
	`Tur` TINYINT(1) NULL DEFAULT '1' COMMENT '0 ise Merkez,1 ise Şube',
	`SubeAdi` VARCHAR(150) NULL DEFAULT NULL COLLATE 'latin5_turkish_ci',
	`IlIlce` VARCHAR(150) NULL DEFAULT NULL COLLATE 'latin5_turkish_ci',
	`KayitTarihi` DATETIME NULL DEFAULT NULL,
	`BitisTarihi` DATETIME NULL DEFAULT NULL,
	`GuncellemeTarihi` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	`YetkiliAdiSoyadi` VARCHAR(50) NULL DEFAULT NULL COLLATE 'latin5_turkish_ci',
	`Telefon` VARCHAR(50) NULL DEFAULT NULL COLLATE 'latin5_turkish_ci',
	`GsmNo` VARCHAR(50) NULL DEFAULT NULL COLLATE 'latin5_turkish_ci',
	`Onay` TINYINT(1) NULL DEFAULT '1',
	`CaptchaKontor` INT(10) NULL DEFAULT '0',
	`SubeLogo` VARCHAR(80) NULL DEFAULT NULL COLLATE 'latin5_turkish_ci',
	`Silinmismi` TINYINT(1) NULL DEFAULT '0',
	`SilinmeTarihi` DATETIME NULL DEFAULT NULL,
	`SilenUyeId` INT(10) NULL DEFAULT NULL,
	UNIQUE INDEX `ID` (`ID`) USING BTREE,
	INDEX `SubeAdi` (`SubeAdi`) USING BTREE,
	INDEX `FirmaId` (`FirmaId`) USING BTREE,
	INDEX `Tur` (`Tur`) USING BTREE,
	INDEX `YetkiliAdiSoyadi` (`YetkiliAdiSoyadi`) USING BTREE,
	INDEX `Onay` (`Onay`) USING BTREE
)
COLLATE='latin5_turkish_ci'
ENGINE=MyISAM
ROW_FORMAT=DYNAMIC
AUTO_INCREMENT=11828
;


firma listesi

CREATE TABLE `sigortafirmalist` (
	`Id` INT(10) NOT NULL AUTO_INCREMENT,
	`UstId` INT(10) NULL DEFAULT NULL,
	`Tur` TINYINT(1) NULL DEFAULT '1',
	`FirmaAdi` VARCHAR(150) NULL DEFAULT NULL COLLATE 'latin5_turkish_ci',
	`FirmaAciklamasi` VARCHAR(150) NULL DEFAULT NULL COLLATE 'latin5_turkish_ci',
	`WebDomain` VARCHAR(50) NULL DEFAULT NULL COLLATE 'latin5_turkish_ci',
	`Ililce` VARCHAR(150) NULL DEFAULT NULL COLLATE 'latin5_turkish_ci',
	`KayitTarihi` DATETIME NULL DEFAULT NULL,
	`BitisTarihi` DATETIME NULL DEFAULT NULL,
	`GuncellemeTarihi` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	`YetkiliAdiSoyadi` VARCHAR(50) NULL DEFAULT NULL COLLATE 'latin5_turkish_ci',
	`Telefon` VARCHAR(50) NULL DEFAULT NULL COLLATE 'latin5_turkish_ci',
	`GsmNo` VARCHAR(50) NULL DEFAULT NULL COLLATE 'latin5_turkish_ci',
	`Onay` TINYINT(1) NULL DEFAULT '1',
	`SatinAldiMi` INT(10) NOT NULL DEFAULT '0',
	`SozlesmeDurumu` TINYINT(1) NOT NULL DEFAULT '0',
	`AcentaSirketi` VARCHAR(80) NULL DEFAULT NULL COLLATE 'latin5_turkish_ci',
	`AcentaKodu` VARCHAR(20) NULL DEFAULT NULL COLLATE 'latin5_turkish_ci',
	`MaksimumKullaniciSayisi` INT(2) NOT NULL DEFAULT '0',
	`SatinAlinanMasaustuKullanicisi` INT(2) NOT NULL DEFAULT '0',
	`MaksimumWebKullaniciSayisi` INT(2) NOT NULL DEFAULT '0',
	`SatinAlinanWebKullanicisi` INT(2) NOT NULL DEFAULT '0',
	`MaksimumSirketSayisi` INT(2) NOT NULL DEFAULT '0',
	`SatinAlinanTrafikSirketiSayisi` INT(2) NOT NULL DEFAULT '0',
	`MaksimumKaskoSirketSayisi` INT(2) NOT NULL DEFAULT '0',
	`SatinAlinanKaskoSirketiSayisi` INT(2) NOT NULL DEFAULT '0',
	`MaksimumSaglikSirketSayisi` INT(2) NOT NULL DEFAULT '0',
	`SatinAlinanSaglikSirketiSayisi` INT(2) NOT NULL DEFAULT '0',
	`KaskoUyariDurumu` INT(2) NOT NULL DEFAULT '0',
	`SozlesmeGondermeDurumu` TINYINT(1) NOT NULL DEFAULT '0',
	`FirmaLogosu` VARCHAR(50) NULL DEFAULT NULL COLLATE 'latin5_turkish_ci',
	`CaptchaKontor` INT(1) NULL DEFAULT '0',
	`ProxyDurumu` VARCHAR(300) NULL DEFAULT NULL COLLATE 'latin5_turkish_ci',
	`SonKesilenPoliceTarihi` DATETIME NULL DEFAULT NULL,
	`SMSSirketi` VARCHAR(50) NULL DEFAULT NULL COLLATE 'latin5_turkish_ci',
	`SMSKullaniciAdi` VARCHAR(50) NULL DEFAULT NULL COLLATE 'latin5_turkish_ci',
	`SMSParola` VARCHAR(50) NULL DEFAULT NULL COLLATE 'latin5_turkish_ci',
	`SMSBaslik` VARCHAR(50) NULL DEFAULT NULL COLLATE 'latin5_turkish_ci',
	`SMSAboneNo` VARCHAR(12) NULL DEFAULT NULL COLLATE 'latin5_turkish_ci',
	`FeedbackLink` VARCHAR(20) NULL DEFAULT NULL COLLATE 'latin5_turkish_ci',
	`FeedbackMainFirmId` INT(10) NULL DEFAULT '0',
	`OncelikNotu` TINYINT(2) NULL DEFAULT '0',
	`NeoSinerji` TINYINT(1) NULL DEFAULT '0',
	`KVKKBilgilendirildimi` TINYINT(1) NULL DEFAULT '0',
	`OtonomAgentId` INT(11) NULL DEFAULT '-1',
	`MuhasebeMusteriBilgisiTut` TINYINT(1) NULL DEFAULT '0',
	`ExcelTopluSorguBilgilendirildimi` TINYINT(1) NULL DEFAULT '0',
	`CasperBilgilendirildimi` TINYINT(1) NULL DEFAULT '0',
	`EkstraSirketUyarisiVerilmesi` TINYINT(1) NULL DEFAULT '0',
	`HesaplardaSifrelerGizlensin` TINYINT(1) NULL DEFAULT '0',
	`MobilAssistance` TINYINT(1) NULL DEFAULT '0',
	`GirisYapilabilecekProgram` TINYINT(1) NULL DEFAULT '2',
	`SahibiAdiSoyadi` VARCHAR(100) NULL DEFAULT NULL COLLATE 'latin5_turkish_ci',
	`SahibiEmail` VARCHAR(50) NULL DEFAULT NULL COLLATE 'latin5_turkish_ci',
	`SahibiGSM` VARCHAR(10) NULL DEFAULT NULL COLLATE 'latin5_turkish_ci',
	`MuhasebeAdiSoyadi` VARCHAR(100) NULL DEFAULT NULL COLLATE 'latin5_turkish_ci',
	`MuhasebeEmail` VARCHAR(50) NULL DEFAULT NULL COLLATE 'latin5_turkish_ci',
	`MuhasebeGSM` VARCHAR(10) NULL DEFAULT NULL COLLATE 'latin5_turkish_ci',
	`BilgiIslemAdiSoyadi` VARCHAR(100) NULL DEFAULT NULL COLLATE 'latin5_turkish_ci',
	`BilgiIslemEmail` VARCHAR(50) NULL DEFAULT NULL COLLATE 'latin5_turkish_ci',
	`BilgiIslemGSM` VARCHAR(10) NULL DEFAULT NULL COLLATE 'latin5_turkish_ci',
	`AnadoluAgencyCode` VARCHAR(10) NULL DEFAULT NULL COLLATE 'latin5_turkish_ci',
	`AnadoluClientSecret` VARCHAR(50) NULL DEFAULT NULL COLLATE 'latin5_turkish_ci',
	`AnadoluClientId` VARCHAR(50) NULL DEFAULT NULL COLLATE 'latin5_turkish_ci',
	`VarsayilanMuhasebeYetkiId` INT(7) NULL DEFAULT '-1',
	`SigortaOnlineFirmInformationId` TINYINT(4) NULL DEFAULT NULL,
	`OtonomAgentKullanabilecek` TINYINT(4) NULL DEFAULT '0',
	`WhatsAppAPIURL` VARCHAR(100) NULL DEFAULT NULL COLLATE 'latin5_turkish_ci',
	`PoliceTalepleriEmaili` VARCHAR(100) NULL DEFAULT NULL COLLATE 'latin5_turkish_ci',
	`PoliceTalepleriGsm` VARCHAR(200) NULL DEFAULT NULL COLLATE 'latin5_turkish_ci',
	PRIMARY KEY (`Id`) USING BTREE,
	UNIQUE INDEX `Domain` (`WebDomain`) USING BTREE
)
COLLATE='latin5_turkish_ci'
ENGINE=MyISAM
AUTO_INCREMENT=710
;

acente kodlari

CREATE TABLE `muhasebe_acentekodlari` (
	`ID` INT(11) NOT NULL AUTO_INCREMENT,
	`SigortaSirketiId` INT(3) NOT NULL,
	`AcenteKodu` VARCHAR(15) NOT NULL COLLATE 'latin5_turkish_ci',
	`AcenteAdi` VARCHAR(70) NOT NULL COLLATE 'latin5_turkish_ci',
	`DisAcente` TINYINT(4) NOT NULL DEFAULT '0',
	`FirmaId` INT(11) NOT NULL,
	`UyeId` INT(11) NOT NULL,
	`GuncelleyenUyeId` INT(11) NOT NULL,
	`EklenmeTarihi` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
	`GuncellenmeTarihi` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	`OtomatikEklendi` CHAR(1) NULL DEFAULT '0' COLLATE 'latin5_turkish_ci',
	PRIMARY KEY (`ID`) USING BTREE,
	INDEX `idx_AcenteKodu` (`AcenteKodu`) USING BTREE,
	INDEX `idx_AcenteAdi` (`AcenteAdi`) USING BTREE,
	INDEX `idx_FirmaId` (`FirmaId`) USING BTREE,
	INDEX `idx_UyeId` (`UyeId`) USING BTREE,
	INDEX `OtomatikEklendi` (`OtomatikEklendi`) USING BTREE,
	INDEX `idx_DisAcente` (`DisAcente`) USING BTREE
)
COLLATE='latin5_turkish_ci'
ENGINE=InnoDB
AUTO_INCREMENT=4211
;


Komisyon Oranları

CREATE TABLE `muhasebe_komisyonoranlari_v2` (
	`ID` INT(11) NOT NULL AUTO_INCREMENT,
	`KomisyonGrupID` INT(11) NOT NULL COMMENT 'muhasebe_komisyongruplari.ID referansı',
	`FirmaID` INT(11) NOT NULL,
	`SigortaSirketiId` INT(11) NOT NULL COMMENT 'muhasebe_sigortasirketi.Id referansı',
	`BransId` TINYINT(4) NOT NULL COMMENT '0=Trafik, 1=Kasko, 2=Dask, 3=FerdiKaza, 4=Koltuk, 5=Konut, 6=Nakliyat, 7=SeyahatSaglik, 8=TamamlayiciSaglik, 9=YabanciSaglik, 10=Imm',
	`KomisyonOrani` TINYINT(4) NOT NULL DEFAULT '0' COMMENT 'Yüzde olarak komisyon oranı (0-100)',
	`EkleyenUyeID` INT(11) NULL DEFAULT NULL,
	`GuncelleyenUyeID` INT(11) NULL DEFAULT NULL,
	`EklenmeTarihi` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
	`GuncellenmeTarihi` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (`ID`) USING BTREE,
	UNIQUE INDEX `uk_grup_sirket_brans` (`KomisyonGrupID`, `SigortaSirketiId`, `BransId`) USING BTREE,
	INDEX `idx_FirmaID` (`FirmaID`) USING BTREE,
	INDEX `idx_SigortaSirketiId` (`SigortaSirketiId`) USING BTREE,
	INDEX `idx_KomisyonGrupID` (`KomisyonGrupID`) USING BTREE,
	INDEX `idx_BransId` (`BransId`) USING BTREE,
	CONSTRAINT `fk_komisyon_grup` FOREIGN KEY (`KomisyonGrupID`) REFERENCES `muhasebe_komisyongruplari` (`ID`) ON UPDATE CASCADE ON DELETE CASCADE
)
COMMENT='Normalize komisyon oranları. Eski 420+ kolonlu tablo yerine satır bazlı yapı.'
COLLATE='utf8_turkish_ci'
ENGINE=InnoDB
;


CREATE TABLE `muhasebe_komisyonoranlari` (
	`ID` INT(11) NOT NULL AUTO_INCREMENT,
	`EkleyenUyeID` INT(11) NOT NULL DEFAULT '0',
	`GuncelleyenUyeID` INT(11) NOT NULL DEFAULT '0',
	`FirmaID` INT(11) NOT NULL DEFAULT '0',
	`EklenmeTarihi` DATETIME NOT NULL,
	`GuncellenmeTarihi` DATETIME NULL DEFAULT NULL,
	`AcnTurkTrafikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`AcnTurkKaskoKomisyon` TINYINT(2) NULL DEFAULT '0',
	`AcnTurkDaskKomisyon` TINYINT(2) NULL DEFAULT '0',
	`AcnTurkFerdiKazaKomisyon` TINYINT(2) NULL DEFAULT '0',
	`AcnTurkKoltukKomisyon` TINYINT(2) NULL DEFAULT '0',
	`AcnTurkKonutKomisyon` TINYINT(2) NULL DEFAULT '0',
	`AcnTurkNakliyatKomisyon` TINYINT(2) NULL DEFAULT '0',
	`AcnTurkSeyahatSaglikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`AcnTurkTamamlayiciSaglikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`AcnTurkYabanciSaglikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`AcnTurkImmKomisyon` TINYINT(2) NULL DEFAULT '0',
	`AkTrafikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`AkKaskoKomisyon` TINYINT(2) NULL DEFAULT '0',
	`AkDaskKomisyon` TINYINT(2) NULL DEFAULT '0',
	`AkFerdiKazaKomisyon` TINYINT(2) NULL DEFAULT '0',
	`AkKoltukKomisyon` TINYINT(2) NULL DEFAULT '0',
	`AkKonutKomisyon` TINYINT(2) NULL DEFAULT '0',
	`AkNakliyatKomisyon` TINYINT(2) NULL DEFAULT '0',
	`AkSeyahatSaglikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`AkTamamlayiciSaglikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`AkYabanciSaglikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`AkImmKomisyon` TINYINT(2) NULL DEFAULT '0',
	`AllianzTrafikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`AllianzKaskoKomisyon` TINYINT(2) NULL DEFAULT '0',
	`AllianzDaskKomisyon` TINYINT(2) NULL DEFAULT '0',
	`AllianzFerdiKazaKomisyon` TINYINT(2) NULL DEFAULT '0',
	`AllianzKoltukKomisyon` TINYINT(2) NULL DEFAULT '0',
	`AllianzKonutKomisyon` TINYINT(2) NULL DEFAULT '0',
	`AllianzNakliyatKomisyon` TINYINT(2) NULL DEFAULT '0',
	`AllianzSeyahatSaglikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`AllianzTamamlayiciSaglikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`AllianzYabanciSaglikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`AllianzImmKomisyon` TINYINT(2) NULL DEFAULT '0',
	`AnaTrafikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`AnaKaskoKomisyon` TINYINT(2) NULL DEFAULT '0',
	`AnaDaskKomisyon` TINYINT(2) NULL DEFAULT '0',
	`AnaFerdiKazaKomisyon` TINYINT(2) NULL DEFAULT '0',
	`AnaKoltukKomisyon` TINYINT(2) NULL DEFAULT '0',
	`AnaKonutKomisyon` TINYINT(2) NULL DEFAULT '0',
	`AnaNakliyatKomisyon` TINYINT(2) NULL DEFAULT '0',
	`AnaSeyahatSaglikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`AnaTamamlayiciSaglikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`AnaYabanciSaglikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`AnaImmKomisyon` TINYINT(2) NULL DEFAULT '0',
	`AnadoluTrafikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`AnadoluKaskoKomisyon` TINYINT(2) NULL DEFAULT '0',
	`AnadoluDaskKomisyon` TINYINT(2) NULL DEFAULT '0',
	`AnadoluFerdiKazaKomisyon` TINYINT(2) NULL DEFAULT '0',
	`AnadoluKoltukKomisyon` TINYINT(2) NULL DEFAULT '0',
	`AnadoluKonutKomisyon` TINYINT(2) NULL DEFAULT '0',
	`AnadoluNakliyatKomisyon` TINYINT(2) NULL DEFAULT '0',
	`AnadoluSeyahatSaglikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`AnadoluTamamlayiciSaglikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`AnadoluYabanciSaglikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`AnadoluImmKomisyon` TINYINT(2) NULL DEFAULT '0',
	`AnkaraTrafikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`AnkaraKaskoKomisyon` TINYINT(2) NULL DEFAULT '0',
	`AnkaraDaskKomisyon` TINYINT(2) NULL DEFAULT '0',
	`AnkaraFerdiKazaKomisyon` TINYINT(2) NULL DEFAULT '0',
	`AnkaraKoltukKomisyon` TINYINT(2) NULL DEFAULT '0',
	`AnkaraKonutKomisyon` TINYINT(2) NULL DEFAULT '0',
	`AnkaraNakliyatKomisyon` TINYINT(2) NULL DEFAULT '0',
	`AnkaraSeyahatSaglikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`AnkaraTamamlayiciSaglikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`AnkaraYabanciSaglikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`AnkaraImmKomisyon` TINYINT(2) NULL DEFAULT '0',
	`ArexTrafikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`ArexKaskoKomisyon` TINYINT(2) NULL DEFAULT '0',
	`ArexDaskKomisyon` TINYINT(2) NULL DEFAULT '0',
	`ArexFerdiKazaKomisyon` TINYINT(2) NULL DEFAULT '0',
	`ArexKoltukKomisyon` TINYINT(2) NULL DEFAULT '0',
	`ArexKonutKomisyon` TINYINT(2) NULL DEFAULT '0',
	`ArexNakliyatKomisyon` TINYINT(2) NULL DEFAULT '0',
	`ArexSeyahatSaglikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`ArexTamamlayiciSaglikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`ArexYabanciSaglikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`ArexImmKomisyon` TINYINT(2) NULL DEFAULT '0',
	`AtlasTrafikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`AtlasKaskoKomisyon` TINYINT(2) NULL DEFAULT '0',
	`AtlasDaskKomisyon` TINYINT(2) NULL DEFAULT '0',
	`AtlasFerdiKazaKomisyon` TINYINT(2) NULL DEFAULT '0',
	`AtlasKoltukKomisyon` TINYINT(2) NULL DEFAULT '0',
	`AtlasKonutKomisyon` TINYINT(2) NULL DEFAULT '0',
	`AtlasNakliyatKomisyon` TINYINT(2) NULL DEFAULT '0',
	`AtlasSeyahatSaglikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`AtlasTamamlayiciSaglikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`AtlasYabanciSaglikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`AtlasImmKomisyon` TINYINT(2) NULL DEFAULT '0',
	`AveonTrafikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`AveonKaskoKomisyon` TINYINT(2) NULL DEFAULT '0',
	`AveonDaskKomisyon` TINYINT(2) NULL DEFAULT '0',
	`AveonFerdiKazaKomisyon` TINYINT(2) NULL DEFAULT '0',
	`AveonKoltukKomisyon` TINYINT(2) NULL DEFAULT '0',
	`AveonKonutKomisyon` TINYINT(2) NULL DEFAULT '0',
	`AveonNakliyatKomisyon` TINYINT(2) NULL DEFAULT '0',
	`AveonSeyahatSaglikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`AveonTamamlayiciSaglikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`AveonYabanciSaglikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`AveonImmKomisyon` TINYINT(2) NULL DEFAULT '0',
	`AxaTrafikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`AxaKaskoKomisyon` TINYINT(2) NULL DEFAULT '0',
	`AxaDaskKomisyon` TINYINT(2) NULL DEFAULT '0',
	`AxaFerdiKazaKomisyon` TINYINT(2) NULL DEFAULT '0',
	`AxaKoltukKomisyon` TINYINT(2) NULL DEFAULT '0',
	`AxaKonutKomisyon` TINYINT(2) NULL DEFAULT '0',
	`AxaNakliyatKomisyon` TINYINT(2) NULL DEFAULT '0',
	`AxaSeyahatSaglikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`AxaTamamlayiciSaglikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`AxaYabanciSaglikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`AxaImmKomisyon` TINYINT(2) NULL DEFAULT '0',
	`BereketTrafikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`BereketKaskoKomisyon` TINYINT(2) NULL DEFAULT '0',
	`BereketDaskKomisyon` TINYINT(2) NULL DEFAULT '0',
	`BereketFerdiKazaKomisyon` TINYINT(2) NULL DEFAULT '0',
	`BereketKoltukKomisyon` TINYINT(2) NULL DEFAULT '0',
	`BereketKonutKomisyon` TINYINT(2) NULL DEFAULT '0',
	`BereketNakliyatKomisyon` TINYINT(2) NULL DEFAULT '0',
	`BereketSeyahatSaglikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`BereketTamamlayiciSaglikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`BereketYabanciSaglikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`BereketImmKomisyon` TINYINT(2) NULL DEFAULT '0',
	`CorpusTrafikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`CorpusKaskoKomisyon` TINYINT(2) NULL DEFAULT '0',
	`CorpusDaskKomisyon` TINYINT(2) NULL DEFAULT '0',
	`CorpusFerdiKazaKomisyon` TINYINT(2) NULL DEFAULT '0',
	`CorpusKoltukKomisyon` TINYINT(2) NULL DEFAULT '0',
	`CorpusKonutKomisyon` TINYINT(2) NULL DEFAULT '0',
	`CorpusNakliyatKomisyon` TINYINT(2) NULL DEFAULT '0',
	`CorpusSeyahatSaglikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`CorpusTamamlayiciSaglikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`CorpusYabanciSaglikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`CorpusImmKomisyon` TINYINT(2) NULL DEFAULT '0',
	`DogaTrafikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`DogaKaskoKomisyon` TINYINT(2) NULL DEFAULT '0',
	`DogaDaskKomisyon` TINYINT(2) NULL DEFAULT '0',
	`DogaFerdiKazaKomisyon` TINYINT(2) NULL DEFAULT '0',
	`DogaKoltukKomisyon` TINYINT(2) NULL DEFAULT '0',
	`DogaKonutKomisyon` TINYINT(2) NULL DEFAULT '0',
	`DogaNakliyatKomisyon` TINYINT(2) NULL DEFAULT '0',
	`DogaSeyahatSaglikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`DogaTamamlayiciSaglikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`DogaYabanciSaglikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`DogaImmKomisyon` TINYINT(2) NULL DEFAULT '0',
	`EmaaTrafikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`EmaaKaskoKomisyon` TINYINT(2) NULL DEFAULT '0',
	`EmaaDaskKomisyon` TINYINT(2) NULL DEFAULT '0',
	`EmaaFerdiKazaKomisyon` TINYINT(2) NULL DEFAULT '0',
	`EmaaKoltukKomisyon` TINYINT(2) NULL DEFAULT '0',
	`EmaaKonutKomisyon` TINYINT(2) NULL DEFAULT '0',
	`EmaaNakliyatKomisyon` TINYINT(2) NULL DEFAULT '0',
	`EmaaSeyahatSaglikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`EmaaTamamlayiciSaglikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`EmaaYabanciSaglikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`EmaaImmKomisyon` TINYINT(2) NULL DEFAULT '0',
	`EthicaTrafikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`EthicaKaskoKomisyon` TINYINT(2) NULL DEFAULT '0',
	`EthicaDaskKomisyon` TINYINT(2) NULL DEFAULT '0',
	`EthicaFerdiKazaKomisyon` TINYINT(2) NULL DEFAULT '0',
	`EthicaKoltukKomisyon` TINYINT(2) NULL DEFAULT '0',
	`EthicaKonutKomisyon` TINYINT(2) NULL DEFAULT '0',
	`EthicaNakliyatKomisyon` TINYINT(2) NULL DEFAULT '0',
	`EthicaSeyahatSaglikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`EthicaTamamlayiciSaglikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`EthicaYabanciSaglikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`EthicaImmKomisyon` TINYINT(2) NULL DEFAULT '0',
	`EurekoTrafikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`EurekoKaskoKomisyon` TINYINT(2) NULL DEFAULT '0',
	`EurekoDaskKomisyon` TINYINT(2) NULL DEFAULT '0',
	`EurekoFerdiKazaKomisyon` TINYINT(2) NULL DEFAULT '0',
	`EurekoKoltukKomisyon` TINYINT(2) NULL DEFAULT '0',
	`EurekoKonutKomisyon` TINYINT(2) NULL DEFAULT '0',
	`EurekoNakliyatKomisyon` TINYINT(2) NULL DEFAULT '0',
	`EurekoSeyahatSaglikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`EurekoTamamlayiciSaglikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`EurekoYabanciSaglikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`EurekoImmKomisyon` TINYINT(2) NULL DEFAULT '0',
	`GriTrafikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`GriKaskoKomisyon` TINYINT(2) NULL DEFAULT '0',
	`GriDaskKomisyon` TINYINT(2) NULL DEFAULT '0',
	`GriFerdiKazaKomisyon` TINYINT(2) NULL DEFAULT '0',
	`GriKoltukKomisyon` TINYINT(2) NULL DEFAULT '0',
	`GriKonutKomisyon` TINYINT(2) NULL DEFAULT '0',
	`GriNakliyatKomisyon` TINYINT(2) NULL DEFAULT '0',
	`GriSeyahatSaglikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`GriTamamlayiciSaglikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`GriYabanciSaglikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`GriImmKomisyon` TINYINT(2) NULL DEFAULT '0',
	`GroupamaTrafikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`GroupamaKaskoKomisyon` TINYINT(2) NULL DEFAULT '0',
	`GroupamaDaskKomisyon` TINYINT(2) NULL DEFAULT '0',
	`GroupamaFerdiKazaKomisyon` TINYINT(2) NULL DEFAULT '0',
	`GroupamaKoltukKomisyon` TINYINT(2) NULL DEFAULT '0',
	`GroupamaKonutKomisyon` TINYINT(2) NULL DEFAULT '0',
	`GroupamaNakliyatKomisyon` TINYINT(2) NULL DEFAULT '0',
	`GroupamaSeyahatSaglikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`GroupamaTamamlayiciSaglikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`GroupamaYabanciSaglikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`GroupamaImmKomisyon` TINYINT(2) NULL DEFAULT '0',
	`GulfTrafikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`GulfKaskoKomisyon` TINYINT(2) NULL DEFAULT '0',
	`GulfDaskKomisyon` TINYINT(2) NULL DEFAULT '0',
	`GulfFerdiKazaKomisyon` TINYINT(2) NULL DEFAULT '0',
	`GulfKoltukKomisyon` TINYINT(2) NULL DEFAULT '0',
	`GulfKonutKomisyon` TINYINT(2) NULL DEFAULT '0',
	`GulfNakliyatKomisyon` TINYINT(2) NULL DEFAULT '0',
	`GulfSeyahatSaglikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`GulfTamamlayiciSaglikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`GulfYabanciSaglikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`GulfImmKomisyon` TINYINT(2) NULL DEFAULT '0',
	`HDITrafikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`HDIKaskoKomisyon` TINYINT(2) NULL DEFAULT '0',
	`HDIDaskKomisyon` TINYINT(2) NULL DEFAULT '0',
	`HDIFerdiKazaKomisyon` TINYINT(2) NULL DEFAULT '0',
	`HDIKoltukKomisyon` TINYINT(2) NULL DEFAULT '0',
	`HDIKonutKomisyon` TINYINT(2) NULL DEFAULT '0',
	`HDINakliyatKomisyon` TINYINT(2) NULL DEFAULT '0',
	`HDISeyahatSaglikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`HDITamamlayiciSaglikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`HDIYabanciSaglikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`HDIImmKomisyon` TINYINT(2) NULL DEFAULT '0',
	`HepiyiTrafikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`HepiyiKaskoKomisyon` TINYINT(2) NULL DEFAULT '0',
	`HepiyiDaskKomisyon` TINYINT(2) NULL DEFAULT '0',
	`HepiyiFerdiKazaKomisyon` TINYINT(2) NULL DEFAULT '0',
	`HepiyiKoltukKomisyon` TINYINT(2) NULL DEFAULT '0',
	`HepiyiKonutKomisyon` TINYINT(2) NULL DEFAULT '0',
	`HepiyiNakliyatKomisyon` TINYINT(2) NULL DEFAULT '0',
	`HepiyiSeyahatSaglikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`HepiyiTamamlayiciSaglikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`HepiyiYabanciSaglikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`HepiyiImmKomisyon` TINYINT(2) NULL DEFAULT '0',
	`KoruTrafikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`KoruKaskoKomisyon` TINYINT(2) NULL DEFAULT '0',
	`KoruDaskKomisyon` TINYINT(2) NULL DEFAULT '0',
	`KoruFerdiKazaKomisyon` TINYINT(2) NULL DEFAULT '0',
	`KoruKoltukKomisyon` TINYINT(2) NULL DEFAULT '0',
	`KoruKonutKomisyon` TINYINT(2) NULL DEFAULT '0',
	`KoruNakliyatKomisyon` TINYINT(2) NULL DEFAULT '0',
	`KoruSeyahatSaglikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`KoruTamamlayiciSaglikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`KoruYabanciSaglikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`KoruImmKomisyon` TINYINT(2) NULL DEFAULT '0',
	`MagdeburgerTrafikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`MagdeburgerKaskoKomisyon` TINYINT(2) NULL DEFAULT '0',
	`MagdeburgerDaskKomisyon` TINYINT(2) NULL DEFAULT '0',
	`MagdeburgerFerdiKazaKomisyon` TINYINT(2) NULL DEFAULT '0',
	`MagdeburgerKoltukKomisyon` TINYINT(2) NULL DEFAULT '0',
	`MagdeburgerKonutKomisyon` TINYINT(2) NULL DEFAULT '0',
	`MagdeburgerNakliyatKomisyon` TINYINT(2) NULL DEFAULT '0',
	`MagdeburgerSeyahatSaglikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`MagdeburgerTamamlayiciSaglikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`MagdeburgerYabanciSaglikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`MagdeburgerImmKomisyon` TINYINT(2) NULL DEFAULT '0',
	`MapfreTrafikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`MapfreKaskoKomisyon` TINYINT(2) NULL DEFAULT '0',
	`MapfreDaskKomisyon` TINYINT(2) NULL DEFAULT '0',
	`MapfreFerdiKazaKomisyon` TINYINT(2) NULL DEFAULT '0',
	`MapfreKoltukKomisyon` TINYINT(2) NULL DEFAULT '0',
	`MapfreKonutKomisyon` TINYINT(2) NULL DEFAULT '0',
	`MapfreNakliyatKomisyon` TINYINT(2) NULL DEFAULT '0',
	`MapfreSeyahatSaglikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`MapfreTamamlayiciSaglikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`MapfreYabanciSaglikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`MapfreImmKomisyon` TINYINT(2) NULL DEFAULT '0',
	`MellceTrafikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`MellceKaskoKomisyon` TINYINT(2) NULL DEFAULT '0',
	`MellceDaskKomisyon` TINYINT(2) NULL DEFAULT '0',
	`MellceFerdiKazaKomisyon` TINYINT(2) NULL DEFAULT '0',
	`MellceKoltukKomisyon` TINYINT(2) NULL DEFAULT '0',
	`MellceKonutKomisyon` TINYINT(2) NULL DEFAULT '0',
	`MellceNakliyatKomisyon` TINYINT(2) NULL DEFAULT '0',
	`MellceSeyahatSaglikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`MellceTamamlayiciSaglikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`MellceYabanciSaglikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`MellceImmKomisyon` TINYINT(2) NULL DEFAULT '0',
	`NeovaTrafikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`NeovaKaskoKomisyon` TINYINT(2) NULL DEFAULT '0',
	`NeovaDaskKomisyon` TINYINT(2) NULL DEFAULT '0',
	`NeovaFerdiKazaKomisyon` TINYINT(2) NULL DEFAULT '0',
	`NeovaKoltukKomisyon` TINYINT(2) NULL DEFAULT '0',
	`NeovaKonutKomisyon` TINYINT(2) NULL DEFAULT '0',
	`NeovaNakliyatKomisyon` TINYINT(2) NULL DEFAULT '0',
	`NeovaSeyahatSaglikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`NeovaTamamlayiciSaglikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`NeovaYabanciSaglikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`NeovaImmKomisyon` TINYINT(2) NULL DEFAULT '0',
	`OrientTrafikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`OrientKaskoKomisyon` TINYINT(2) NULL DEFAULT '0',
	`OrientDaskKomisyon` TINYINT(2) NULL DEFAULT '0',
	`OrientFerdiKazaKomisyon` TINYINT(2) NULL DEFAULT '0',
	`OrientKoltukKomisyon` TINYINT(2) NULL DEFAULT '0',
	`OrientKonutKomisyon` TINYINT(2) NULL DEFAULT '0',
	`OrientNakliyatKomisyon` TINYINT(2) NULL DEFAULT '0',
	`OrientSeyahatSaglikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`OrientTamamlayiciSaglikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`OrientYabanciSaglikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`OrientImmKomisyon` TINYINT(2) NULL DEFAULT '0',
	`PriveTrafikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`PriveKaskoKomisyon` TINYINT(2) NULL DEFAULT '0',
	`PriveDaskKomisyon` TINYINT(2) NULL DEFAULT '0',
	`PriveFerdiKazaKomisyon` TINYINT(2) NULL DEFAULT '0',
	`PriveKoltukKomisyon` TINYINT(2) NULL DEFAULT '0',
	`PriveKonutKomisyon` TINYINT(2) NULL DEFAULT '0',
	`PriveNakliyatKomisyon` TINYINT(2) NULL DEFAULT '0',
	`PriveSeyahatSaglikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`PriveTamamlayiciSaglikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`PriveYabanciSaglikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`PriveImmKomisyon` TINYINT(2) NULL DEFAULT '0',
	`QuickTrafikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`QuickKaskoKomisyon` TINYINT(2) NULL DEFAULT '0',
	`QuickDaskKomisyon` TINYINT(2) NULL DEFAULT '0',
	`QuickFerdiKazaKomisyon` TINYINT(2) NULL DEFAULT '0',
	`QuickKoltukKomisyon` TINYINT(2) NULL DEFAULT '0',
	`QuickKonutKomisyon` TINYINT(2) NULL DEFAULT '0',
	`QuickNakliyatKomisyon` TINYINT(2) NULL DEFAULT '0',
	`QuickSeyahatSaglikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`QuickTamamlayiciSaglikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`QuickYabanciSaglikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`QuickImmKomisyon` TINYINT(2) NULL DEFAULT '0',
	`RayTrafikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`RayKaskoKomisyon` TINYINT(2) NULL DEFAULT '0',
	`RayDaskKomisyon` TINYINT(2) NULL DEFAULT '0',
	`RayFerdiKazaKomisyon` TINYINT(2) NULL DEFAULT '0',
	`RayKoltukKomisyon` TINYINT(2) NULL DEFAULT '0',
	`RayKonutKomisyon` TINYINT(2) NULL DEFAULT '0',
	`RayNakliyatKomisyon` TINYINT(2) NULL DEFAULT '0',
	`RaySeyahatSaglikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`RayTamamlayiciSaglikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`RayYabanciSaglikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`RayImmKomisyon` TINYINT(2) NULL DEFAULT '0',
	`ReferansTrafikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`ReferansKaskoKomisyon` TINYINT(2) NULL DEFAULT '0',
	`ReferansDaskKomisyon` TINYINT(2) NULL DEFAULT '0',
	`ReferansFerdiKazaKomisyon` TINYINT(2) NULL DEFAULT '0',
	`ReferansKoltukKomisyon` TINYINT(2) NULL DEFAULT '0',
	`ReferansKonutKomisyon` TINYINT(2) NULL DEFAULT '0',
	`ReferansNakliyatKomisyon` TINYINT(2) NULL DEFAULT '0',
	`ReferansSeyahatSaglikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`ReferansTamamlayiciSaglikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`ReferansYabanciSaglikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`ReferansImmKomisyon` TINYINT(2) NULL DEFAULT '0',
	`SompoTrafikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`SompoKaskoKomisyon` TINYINT(2) NULL DEFAULT '0',
	`SompoDaskKomisyon` TINYINT(2) NULL DEFAULT '0',
	`SompoFerdiKazaKomisyon` TINYINT(2) NULL DEFAULT '0',
	`SompoKoltukKomisyon` TINYINT(2) NULL DEFAULT '0',
	`SompoKonutKomisyon` TINYINT(2) NULL DEFAULT '0',
	`SompoNakliyatKomisyon` TINYINT(2) NULL DEFAULT '0',
	`SompoSeyahatSaglikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`SompoTamamlayiciSaglikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`SompoYabanciSaglikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`SompoImmKomisyon` TINYINT(2) NULL DEFAULT '0',
	`SekerTrafikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`SekerKaskoKomisyon` TINYINT(2) NULL DEFAULT '0',
	`SekerDaskKomisyon` TINYINT(2) NULL DEFAULT '0',
	`SekerFerdiKazaKomisyon` TINYINT(2) NULL DEFAULT '0',
	`SekerKoltukKomisyon` TINYINT(2) NULL DEFAULT '0',
	`SekerKonutKomisyon` TINYINT(2) NULL DEFAULT '0',
	`SekerNakliyatKomisyon` TINYINT(2) NULL DEFAULT '0',
	`SekerSeyahatSaglikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`SekerTamamlayiciSaglikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`SekerYabanciSaglikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`SekerImmKomisyon` TINYINT(2) NULL DEFAULT '0',
	`TurkNipponTrafikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`TurkNipponKaskoKomisyon` TINYINT(2) NULL DEFAULT '0',
	`TurkNipponDaskKomisyon` TINYINT(2) NULL DEFAULT '0',
	`TurkNipponFerdiKazaKomisyon` TINYINT(2) NULL DEFAULT '0',
	`TurkNipponKoltukKomisyon` TINYINT(2) NULL DEFAULT '0',
	`TurkNipponKonutKomisyon` TINYINT(2) NULL DEFAULT '0',
	`TurkNipponNakliyatKomisyon` TINYINT(2) NULL DEFAULT '0',
	`TurkNipponSeyahatSaglikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`TurkNipponTamamlayiciSaglikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`TurkNipponYabanciSaglikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`TurkNipponImmKomisyon` TINYINT(2) NULL DEFAULT '0',
	`TurkiyeTrafikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`TurkiyeKaskoKomisyon` TINYINT(2) NULL DEFAULT '0',
	`TurkiyeDaskKomisyon` TINYINT(2) NULL DEFAULT '0',
	`TurkiyeFerdiKazaKomisyon` TINYINT(2) NULL DEFAULT '0',
	`TurkiyeKoltukKomisyon` TINYINT(2) NULL DEFAULT '0',
	`TurkiyeKonutKomisyon` TINYINT(2) NULL DEFAULT '0',
	`TurkiyeNakliyatKomisyon` TINYINT(2) NULL DEFAULT '0',
	`TurkiyeSeyahatSaglikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`TurkiyeTamamlayiciSaglikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`TurkiyeYabanciSaglikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`TurkiyeImmKomisyon` TINYINT(2) NULL DEFAULT '0',
	`TurkiyeKatilimTrafikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`TurkiyeKatilimKaskoKomisyon` TINYINT(2) NULL DEFAULT '0',
	`TurkiyeKatilimDaskKomisyon` TINYINT(2) NULL DEFAULT '0',
	`TurkiyeKatilimFerdiKazaKomisyon` TINYINT(2) NULL DEFAULT '0',
	`TurkiyeKatilimKoltukKomisyon` TINYINT(2) NULL DEFAULT '0',
	`TurkiyeKatilimKonutKomisyon` TINYINT(2) NULL DEFAULT '0',
	`TurkiyeKatilimNakliyatKomisyon` TINYINT(2) NULL DEFAULT '0',
	`TurkiyeKatilimSeyahatSaglikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`TurkiyeKatilimTamamlayiciSaglikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`TurkiyeKatilimYabanciSaglikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`TurkiyeKatilimImmKomisyon` TINYINT(2) NULL DEFAULT '0',
	`UnicoTrafikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`UnicoKaskoKomisyon` TINYINT(2) NULL DEFAULT '0',
	`UnicoDaskKomisyon` TINYINT(2) NULL DEFAULT '0',
	`UnicoFerdiKazaKomisyon` TINYINT(2) NULL DEFAULT '0',
	`UnicoKoltukKomisyon` TINYINT(2) NULL DEFAULT '0',
	`UnicoKonutKomisyon` TINYINT(2) NULL DEFAULT '0',
	`UnicoNakliyatKomisyon` TINYINT(2) NULL DEFAULT '0',
	`UnicoSeyahatSaglikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`UnicoTamamlayiciSaglikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`UnicoYabanciSaglikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`UnicoImmKomisyon` TINYINT(2) NULL DEFAULT '0',
	`ZurichTrafikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`ZurichKaskoKomisyon` TINYINT(2) NULL DEFAULT '0',
	`ZurichDaskKomisyon` TINYINT(2) NULL DEFAULT '0',
	`ZurichFerdiKazaKomisyon` TINYINT(2) NULL DEFAULT '0',
	`ZurichKoltukKomisyon` TINYINT(2) NULL DEFAULT '0',
	`ZurichKonutKomisyon` TINYINT(2) NULL DEFAULT '0',
	`ZurichNakliyatKomisyon` TINYINT(2) NULL DEFAULT '0',
	`ZurichSeyahatSaglikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`ZurichTamamlayiciSaglikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`ZurichYabanciSaglikKomisyon` TINYINT(2) NULL DEFAULT '0',
	`ZurichImmKomisyon` TINYINT(2) NULL DEFAULT '0',
	UNIQUE INDEX `ID` (`ID`) USING BTREE,
	INDEX `EkleyenUyeID` (`EkleyenUyeID`) USING BTREE,
	INDEX `GuncelleyenUyeID` (`GuncelleyenUyeID`) USING BTREE,
	INDEX `FirmaID` (`FirmaID`) USING BTREE
)
COMMENT='Yeni şirket ekleme\r\nALTER TABLE `muhasebe_komisyonoranlari`\r\n	ADD COLUMN `TurkiyeKatilimTrafikKomisyon` TINYINT(2) NULL DEFAULT \'0\' AFTER `TurkiyeImmKomisyon`,\r\n	ADD COLUMN `TurkiyeKatilimKaskoKomisyon` TINYINT(2) NULL DEFAULT \'0\' AFTER `TurkiyeKatilimTrafikKomisyon`,\r\n	ADD COLUMN `TurkiyeKatilimDaskKomisyon` TINYINT(2) NULL DEFAULT \'0\' AFTER `TurkiyeKatilimKaskoKomisyon`,\r\n	ADD COLUMN `TurkiyeKatilimFerdiKazaKomisyon` TINYINT(2) NULL DEFAULT \'0\' AFTER `TurkiyeKatilimDaskKomisyon`,\r\n	ADD COLUMN `TurkiyeKatilimKoltukKomisyon` TINYINT(2) NULL DEFAULT \'0\' AFTER `TurkiyeKatilimFerdiKazaKomisyon`,\r\n	ADD COLUMN `TurkiyeKatilimKonutKomisyon` TINYINT(2) NULL DEFAULT \'0\' AFTER `TurkiyeKatilimKoltukKomisyon`,\r\n	ADD COLUMN `TurkiyeKatilimNakliyatKomisyon` TINYINT(2) NULL DEFAULT \'0\' AFTER `TurkiyeKatilimKonutKomisyon`,\r\n	ADD COLUMN `TurkiyeKatilimSeyahatSaglikKomisyon` TINYINT(2) NULL DEFAULT \'0\' AFTER `TurkiyeKatilimNakliyatKomisyon`,\r\n	ADD COLUMN `TurkiyeKatilimTamamlayiciSaglikKomisyon` TINYINT(2) NULL DEFAULT \'0\' AFTER `TurkiyeKatilimSeyahatSaglikKomisyon`,\r\n	ADD COLUMN `TurkiyeKatilimYabanciSaglikKomisyon` TINYINT(2) NULL DEFAULT \'0\' AFTER `TurkiyeKatilimTamamlayiciSaglikKomisyon`,\r\n	ADD COLUMN `TurkiyeKatilimImmKomisyon` TINYINT(2) NULL DEFAULT \'0\' AFTER `TurkiyeKatilimYabanciSaglikKomisyon`;'
COLLATE='latin5_turkish_ci'
ENGINE=InnoDB
AUTO_INCREMENT=67
;



